const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const vm=require('vm');const ts=require('typescript');
const source=ts.transpileModule(fs.readFileSync('app/api/admins/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
function setup({denied=0,existing=false,duplicate=false,offline=false}={}){let inserted;let calls=0;const exports={};const users={findOne:async()=>existing?{}:null,createIndex:async()=>{},insertOne:async doc=>{if(duplicate)throw {code:11000};inserted=doc;return {insertedId:{toString:()=> 'new-id'}}}};vm.runInNewContext(source,{exports,require:name=>name==='next/server'?{NextResponse:{json:(data,options={})=>({status:options.status||200,data})}}:name==='@/lib/auth'?{requireApiUser:async roles=>{assert.deepEqual(Array.from(roles),['admin']);return {response:denied?{status:denied}:null}},isValidKmitlEmail:e=>/^[\w.%+-]+@kmitl\.ac\.th$/.test(e),hashPassword:p=>'hashed:'+p}:name==='@/lib/mongodb'?{getDb:async()=>{calls++;if(offline)throw Error('offline');return {collection:()=>users}}}:{} });return {post:body=>exports.POST({json:async()=>body}),inserted:()=>inserted,calls:()=>calls}}
const valid={firstName:' Admin ',lastName:' User ',email:' ADMIN2@KMITL.AC.TH ',password:'TestPass123'};
test('only existing admins may create accounts',async()=>{for(const code of [401,403]){const s=setup({denied:code});assert.equal((await s.post(valid)).status,code);assert.equal(s.calls(),0)}});
test('creates active admin with normalized email and hashed password, without exposing password',async()=>{const s=setup();const r=await s.post({...valid,role:'student'});assert.equal(r.status,201);assert.equal(s.inserted().role,'admin');assert.equal(s.inserted().status,'active');assert.equal(s.inserted().email,'admin2@kmitl.ac.th');assert.equal(s.inserted().passwordHash,'hashed:TestPass123');assert.equal(r.data.admin.passwordHash,undefined);assert.equal(s.inserted().studentId,undefined)});
test('rejects malformed input, wrong email and weak password',async()=>{for(const body of [null,{}, {...valid,email:'admin@example.com'},{...valid,password:'short'},{...valid,firstName:' '},{...valid,password:' '.repeat(8)}]){const s=setup();assert.equal((await s.post(body)).status,400);assert.equal(s.calls(),0)}});
test('rejects existing email and concurrent duplicate insert',async()=>{for(const options of [{existing:true},{duplicate:true}])assert.equal((await setup(options).post(valid)).status,409)});
test('reports database failure without leaking details',async()=>{const r=await setup({offline:true}).post(valid);assert.equal(r.status,500);assert.ok(!r.data.message.includes('offline'))});
